//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalBank.ServiceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessResultadoOfArrayOfUsuarioDtoCOpr4HTC", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceUsuario.Common")]
    [System.SerializableAttribute()]
    public partial class BusinessResultadoOfArrayOfUsuarioDtoCOpr4HTC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppDigitalBank.ServiceUsuario.UsuarioDto[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppDigitalBank.ServiceUsuario.ResultadoOperacion ResultadoOperacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppDigitalBank.ServiceUsuario.UsuarioDto[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppDigitalBank.ServiceUsuario.ResultadoOperacion ResultadoOperacion {
            get {
                return this.ResultadoOperacionField;
            }
            set {
                if ((this.ResultadoOperacionField.Equals(value) != true)) {
                    this.ResultadoOperacionField = value;
                    this.RaisePropertyChanged("ResultadoOperacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDto", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceUsuario.Dtos")]
    [System.SerializableAttribute()]
    public partial class UsuarioDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacion", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceUsuario.Common.Enum")]
    public enum ResultadoOperacion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessResultadoOfUsuarioDtoCOpr4HTC", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceUsuario.Common")]
    [System.SerializableAttribute()]
    public partial class BusinessResultadoOfUsuarioDtoCOpr4HTC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppDigitalBank.ServiceUsuario.UsuarioDto ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppDigitalBank.ServiceUsuario.ResultadoOperacion ResultadoOperacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppDigitalBank.ServiceUsuario.UsuarioDto Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppDigitalBank.ServiceUsuario.ResultadoOperacion ResultadoOperacion {
            get {
                return this.ResultadoOperacionField;
            }
            set {
                if ((this.ResultadoOperacionField.Equals(value) != true)) {
                    this.ResultadoOperacionField = value;
                    this.RaisePropertyChanged("ResultadoOperacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessResultadoOfint", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceUsuario.Common")]
    [System.SerializableAttribute()]
    public partial class BusinessResultadoOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppDigitalBank.ServiceUsuario.ResultadoOperacion ResultadoOperacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppDigitalBank.ServiceUsuario.ResultadoOperacion ResultadoOperacion {
            get {
                return this.ResultadoOperacionField;
            }
            set {
                if ((this.ResultadoOperacionField.Equals(value) != true)) {
                    this.ResultadoOperacionField = value;
                    this.RaisePropertyChanged("ResultadoOperacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.IUsuarioBusiness")]
    public interface IUsuarioBusiness {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Consultar", ReplyAction="http://tempuri.org/IUsuarioBusiness/ConsultarResponse")]
        AppDigitalBank.ServiceUsuario.BusinessResultadoOfArrayOfUsuarioDtoCOpr4HTC Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Consultar", ReplyAction="http://tempuri.org/IUsuarioBusiness/ConsultarResponse")]
        System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfArrayOfUsuarioDtoCOpr4HTC> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IUsuarioBusiness/ObtenerUsuarioPorIdResponse")]
        AppDigitalBank.ServiceUsuario.BusinessResultadoOfUsuarioDtoCOpr4HTC ObtenerUsuarioPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IUsuarioBusiness/ObtenerUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfUsuarioDtoCOpr4HTC> ObtenerUsuarioPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Guardar", ReplyAction="http://tempuri.org/IUsuarioBusiness/GuardarResponse")]
        AppDigitalBank.ServiceUsuario.BusinessResultadoOfint Guardar(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Guardar", ReplyAction="http://tempuri.org/IUsuarioBusiness/GuardarResponse")]
        System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfint> GuardarAsync(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Actualizar", ReplyAction="http://tempuri.org/IUsuarioBusiness/ActualizarResponse")]
        AppDigitalBank.ServiceUsuario.BusinessResultadoOfint Actualizar(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Actualizar", ReplyAction="http://tempuri.org/IUsuarioBusiness/ActualizarResponse")]
        System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfint> ActualizarAsync(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Eliminar", ReplyAction="http://tempuri.org/IUsuarioBusiness/EliminarResponse")]
        AppDigitalBank.ServiceUsuario.BusinessResultadoOfint Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioBusiness/Eliminar", ReplyAction="http://tempuri.org/IUsuarioBusiness/EliminarResponse")]
        System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfint> EliminarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioBusinessChannel : AppDigitalBank.ServiceUsuario.IUsuarioBusiness, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioBusinessClient : System.ServiceModel.ClientBase<AppDigitalBank.ServiceUsuario.IUsuarioBusiness>, AppDigitalBank.ServiceUsuario.IUsuarioBusiness {
        
        public UsuarioBusinessClient() {
        }
        
        public UsuarioBusinessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioBusinessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioBusinessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioBusinessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppDigitalBank.ServiceUsuario.BusinessResultadoOfArrayOfUsuarioDtoCOpr4HTC Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfArrayOfUsuarioDtoCOpr4HTC> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public AppDigitalBank.ServiceUsuario.BusinessResultadoOfUsuarioDtoCOpr4HTC ObtenerUsuarioPorId(int id) {
            return base.Channel.ObtenerUsuarioPorId(id);
        }
        
        public System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfUsuarioDtoCOpr4HTC> ObtenerUsuarioPorIdAsync(int id) {
            return base.Channel.ObtenerUsuarioPorIdAsync(id);
        }
        
        public AppDigitalBank.ServiceUsuario.BusinessResultadoOfint Guardar(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto) {
            return base.Channel.Guardar(usuarioDto);
        }
        
        public System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfint> GuardarAsync(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto) {
            return base.Channel.GuardarAsync(usuarioDto);
        }
        
        public AppDigitalBank.ServiceUsuario.BusinessResultadoOfint Actualizar(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto) {
            return base.Channel.Actualizar(usuarioDto);
        }
        
        public System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfint> ActualizarAsync(AppDigitalBank.ServiceUsuario.UsuarioDto usuarioDto) {
            return base.Channel.ActualizarAsync(usuarioDto);
        }
        
        public AppDigitalBank.ServiceUsuario.BusinessResultadoOfint Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<AppDigitalBank.ServiceUsuario.BusinessResultadoOfint> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
